### ISSUE TITLE
[feat] New Flexbox Controls

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#567] opened 2024-10-16 18:56 UTC
Have an "add" button in the right corner of the flexbox + layout section

<img width="323" alt="image" src="https://github.com/user-attachments/assets/64f50b21-eda3-4671-a40b-f250910a2794">

When the add button is selected, it transitions to a minus button. 
<img width="376" alt="image" src="https://github.com/user-attachments/assets/a91e1254-c559-4b79-9065-2a1498a9f9cb">

this introduces a quad-step button for the horizontal and vertical directions.

**Comment by tanmaytare** [comment] 2024-10-16 21:14
i would like to work on it , can you assign it to me

**Comment by drfarrell** [comment] 2024-10-16 21:31
@tanmaytare is assigned another issue, so for any contributors that would like to take this one on, just let me know!

**Comment by Goutamchoudhary907** [comment] 2024-10-17 02:05
Hey @drfarrell I want to work on this assign me and describe what changes you want

**Comment by alexandreantunesmnds** [comment] 2024-10-17 07:21
Hi @drfarrell can i solve this issue please ?

**Comment by darshancn** [comment] 2024-10-17 10:15
Hey @drfarrell if this is not yet assigned to anyone , i would like to contribute .

**Comment by Kitenite** [comment] 2024-10-17 12:56
Go for it @alexandreantunesmnds !

**Comment by Goutamchoudhary907** [comment] 2024-10-19 10:03
Hey @Kitenite  @drfarrell  can you explain the issue more . What changes i need to do

**Comment by Kitenite** [comment] 2024-10-20 19:24
Hey @Goutamchoudhary907 , 
I will attempt to answer then @drfarrell can fill in. Right now, we have display shown as 3 selectable toggles. 
Instead, when display is block, we'd want to hide that toggle, adding a + instead. When + is clicked, we assign a flex layout and show the rest of the inputs. 

<img width="239" alt="Screenshot 2024-10-20 at 3 23 22 PM" src="https://github.com/user-attachments/assets/8da5f8d9-9a1a-4307-8e96-e83a7c7bce67">

**Comment by drfarrell** [comment] 2024-10-23 19:09
@Goutamchoudhary907 

This is a great example of what we're looking for:

![image](https://github.com/user-attachments/assets/d771ade9-b065-44cd-8ea3-017d5d48a6ce)

As Kiet mentioned, it means removing the [ -- ] button and making a [ + ] button in the upper right corner. Does that makes sense?

**Comment by Goutamchoudhary907** [comment] 2024-10-24 02:29
Yeah thanks for describing , i will work on it

**Comment by drfarrell** [comment] 2024-10-30 22:52
@Goutamchoudhary907 how is it going? Do you need help with anything?

**Comment by Goutamchoudhary907** [comment] 2024-10-31 06:36
@drfarrell I am unable to find the file in which the issue is , can you help

**Comment by Kitenite** [comment] 2024-11-05 20:41
@Goutamchoudhary907 this is the file and location where the style editor inputs are. 
https://github.com/onlook-dev/onlook/blob/05296561fd751639f6262b994a3f7260136b4027/apps/studio/src/routes/editor/EditPanel/StylesTab/index.tsx#L24

You can find the implementation for each style here:
https://github.com/onlook-dev/onlook/blob/05296561fd751639f6262b994a3f7260136b4027/apps/studio/src/lib/editor/styles/group.ts#L1

**Comment by alexandreantunesmnds** [comment] 2024-11-06 19:57
@drfarrell I started working on it can you assign it to me ?

**Comment by alexandreantunesmnds** [comment] 2024-11-06 20:10
@drfarrell Just checking in—is this screenshot close to what you were looking for with the feature? Also, I'm having some trouble getting the +/- elements to match the UI in your example. Let me know if you have any suggestions on that!
![image](https://github.com/user-attachments/assets/ea13d45d-bffe-4aa5-aeec-31796d999f6c)

**Comment by drfarrell** [comment] 2024-11-06 23:47
@alexandreantunesmnds Yes it's getting there – 

For this section, use the Minus icon from our icons on the right. It should be an icon within a button. 
<img width="438" alt="Screenshot 2024-11-06 at 6 42 38 PM" src="https://github.com/user-attachments/assets/cb8de61a-7f40-47cb-a157-515e6a143f80">

Pay attention to this section with four options. You may need to add in icons to the @onlook/ui/icons file from Radix.
<img width="491" alt="Screenshot 2024-11-06 at 6 47 16 PM" src="https://github.com/user-attachments/assets/cb52780e-e46e-413e-b3c4-80146ffc80eb">

**Comment by alexandreantunesmnds** [comment] 2024-11-07 11:47
Hi @drfarrell !  I wanted to reach out for some assistance regarding the issue I'm facing with rendering the four options icons. 

I've added the following code snippet to group.ts for handling the horizontal and vertical alignment options:

`// Horizontal alignment (Justify Content)
new SingleStyleImpl('justifyContent', 'horizontal-start', 'Horizontal', StyleType.Select, {
    options: ['horizontalStart', 'horizontalCenter', 'horizontalEnd', 'horizontalSpaceBetween'],
});

// Vertical alignment (Align Items)
new SingleStyleImpl('alignItems', 'vertical-start', 'Vertical', StyleType.Select, {
    options: ['verticalStart', 'verticalCenter', 'verticalEnd', 'verticalStretch'],
}),
`
In this case, I expect the icons to render for these options, similar to how the icons are rendered for row and column. However, I am facing the issue that, when more than 3 options are provided, the select dropdown does not render the icons properly — it shows text instead.

I've tried the following:

- For options with 3 or fewer entries: The ToggleGroup works fine, displaying the icons correctly.

- For more than 3 options: The icons aren't showing up in the select dropdown, and instead, the option names are displayed as text.

I have already mapped the icon components for each of the options, but I’m still encountering this issue.

`const OVERRIDE_ICONS: Record<string, any> = {
    row: <Icons.ArrowRight />,
    column: <Icons.ArrowDown />,
    horizontalStart: <AlignLeftIcon />,
    horizontalCenter: <AlignCenterHorizontallyIcon />,
    horizontalEnd: <AlignRightIcon />,
    horizontalSpaceBetween: <SpaceBetweenHorizontallyIcon />,
    verticalStart: <AlignTopIcon />,
    verticalCenter: <AlignCenterVerticallyIcon />,
    verticalEnd: <AlignBottomIcon />,
    verticalStretch: <SpaceBetweenVerticallyIcon />,
};

// ToggleGroup for rendering up to 3 options
{elementStyle.params?.options.map((option) => (
    <ToggleGroupItem value={option} key={option}>
        {OVERRIDE_ICONS[option] ?? option}
    </ToggleGroupItem>
))}

// select for rendering more than 3 options
<select name={elementStyle.displayName} value={value} onChange={(event) => handleValueChange(event.currentTarget.value)}>
    {elementStyle.params.options.map((option) => (
        <option value={option} key={option}>
            {OVERRIDE_ICONS[option] ?? option}
        </option>
    ))}
</select>
`

Could you please advise on what might be causing this behavior, and how I can fix it to make sure the icons display properly for all options, even when the number of options exceeds 3?

Thank you so much for your help!

**Comment by Kitenite** [comment] 2024-11-07 14:10
@alexandreantunesmnds,
there's a conditional in the select inputs to render more than 3 options in that way. This was a historical reason to ensure selections look good. It can be updated as needed for your use case as long as the editor remains coherent :)

https://github.com/onlook-dev/onlook/blob/27de540e656c6be24aa0fa6323a4b594106d51c5/apps/studio/src/routes/editor/EditPanel/StylesTab/single/SelectInput.tsx#L123-L126

**Comment by alexandreantunesmnds** [comment] 2024-11-07 15:11
Hi @Kitenite,

Thank you for your help!

I made a PR, but it seems to have conflicts with a file (`bun.lockb`). I don't have write access to resolve it.

https://github.com/onlook-dev/onlook/pull/758

**Comment by alexandreantunesmnds** [comment] 2024-11-07 15:57
@Kitenite Done 👍  Thanks !

**Comment by Kitenite** [comment] 2024-11-07 16:07
Awesome will take a look after my current task. Thanks! @alexandreantunesmnds

**Comment by Kitenite** [comment] 2024-12-29 19:42
Solved!

**Closed by Kitenite** 2024-12-29 19:42 UTC
Labels: enhancement, good first issue, hacktoberfest
