### ISSUE TITLE
[bug] Nothing loads in the canvas on startup

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#327] opened 2024-09-13 17:05 UTC
When a user opens up Onlook for the first time, it is missing the initial frame with the empty state and directions. 

<img width="1111" alt="image" src="https://github.com/user-attachments/assets/a8251025-eb58-4925-9f72-f20e6f02232e">

This may be solved by the new onboarding flow, but that may not be implemented for a bit @Kitenite may be able to provide more context

**Comment by Kitenite** [comment] 2024-09-16 00:23
Duplicate of https://github.com/orgs/onlook-dev/projects/2/views/1?pane=issue&itemId=79762091

**Closed by Kitenite** 2024-09-16 00:23 UTC
Labels: bug, duplicate
