### ISSUE TITLE
[bug] The main window starts off-center on startup

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#307] opened 2024-09-05 21:34 UTC
The window ideally starts in the center of the screen when the app loads, not like the screenshot below

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/2723ee2a-4e95-4684-9a8d-c2ce724da9a0">

**Comment by ahp64** [comment] 2024-09-06 21:03
Can I take this issue?

**Comment by Kitenite** [comment] 2024-09-07 16:19
@ahp64 go for it!

**Comment by stephenm7777** [comment] 2024-09-18 00:07
I can take this if you're cool with it

**Comment by Kitenite** [comment] 2024-09-18 00:16
For sure @stephenm7777 go for it. It might not be very straightforward but happy to talk through a solution

**Comment by Kitenite** [comment] 2024-09-25 19:58
@stephenm7777 , how's it going? Do you need any support on this?

**Comment by ahp64** [comment] 2024-10-03 21:14
Hi, I've been busy the past few weeks but if the issue is still unresolved, I'm more than willing to take it back.

**Comment by Kitenite** [comment] 2024-10-03 22:11
Back at it again, go for it @ahp64 !

**Comment by Kitenite** [comment] 2024-10-06 22:03
Merged @ahp64! Nice work. Shouted you out in the Discord as well :D

**Closed** 2024-10-06 22:08 UTC
Labels: bug, good first issue
